import Html from './assets/html.png';
import Css from './assets/css.png';
import Javascript from './assets/js.png';
import Geografia from './assets/geografia.png';
import Historia from './assets/historia.png';
import Literatura from './assets/literatura.png';
import Tecnologia from './assets/tecnologia.png';

export const imgs = [
  Html,
  Css,
  Javascript,
  Geografia,
  Historia,
  Literatura,
  Tecnologia,
];

export const categories = {
  historia: 'Historia',
  literatura: 'Literatura',
  CSS: 'CSS',
  HTML: 'HTML',
  JS: 'JS',
  tecnologia: 'Tecnologia',
  geografia: 'Geografia',
};

const { historia, tecnologia, literatura, CSS, HTML, JS, geografia } =
  categories;

export const questions = [
  {
    id: 1,
    difficulty: 'Fácil',
    question: '¿Qué evento inició la Primera Guerra Mundial?',
    category: historia,
    correct_answer: 'El asesinato del Archiduque Franz Ferdinand de Austria',
    incorrect_answers: [
      'El hundimiento del Titanic',
      'La invasión de Polonia por Alemania',
      'La Revolución Francesa',
    ],
  },
  {
    id: 2,
    difficulty: 'Fácil',
    question: '¿Quién es el autor de "Cien años de soledad"?        ',
    category: literatura,
    correct_answer: 'Gabriel García Márquez',
    incorrect_answers: ['Julio Cortázar', 'Mario Vargas Llosa', 'Pablo Neruda'],
  },
  {
    id: 3,
    difficulty: 'Fácil',
    question: '¿En qué deporte se utiliza un disco?',
    category: CSS,
    correct_answer: 'Hockey sobre hielo',
    incorrect_answers: ['Fútbol', 'Baloncesto', 'Béisbol'],
  },
  {
    id: 4,
    difficulty: 'Fácil',
    question: '¿Qué significa HTML?',
    category: HTML,
    correct_answer: 'HyperText Markup Language',
    incorrect_answers: [
      ' Hyperlinks and Text Markup Language',
      'Home Tool Markup Language',
      'HyperText and Meta Language',
    ],
  },
  {
    id: 5,
    difficulty: 'Difícil',
    question: '¿Quién es considerado el padre de la filosofía occidental?',
    category: JS,
    correct_answer: 'Sócrates',
    incorrect_answers: ['Aristóteles', 'Platón', 'Nietzsche'],
  },
  {
    id: 6,
    difficulty: 'Medio',
    question: '¿En qué año fue fundada la compañía Apple?',
    category: tecnologia,
    correct_answer: '1976',
    incorrect_answers: ['1984', '1991', '1967'],
  },
  {
    id: 7,
    difficulty: 'Fácil',
    question: '¿Cuál es el río más largo del mundo?',
    category: geografia,
    correct_answer: 'El Río Amazonas',
    incorrect_answers: ['El Río Nilo', 'El Río Yangtze', 'El Río Misisipi'],
  },
  {
    id: 8,
    difficulty: 'Medio',
    question: '¿Cuál es el océano más grande del mundo?',
    category: geografia,
    correct_answer: 'El Océano Pacífico',
    incorrect_answers: [
      'El Océano Atlántico',
      'El Océano Índico',
      'El Océano Ártico',
    ],
  },
  {
    id: 9,
    difficulty: 'Difícil',
    question: '¿Cuál es la obra más famosa de William Shakespeare?',
    category: literatura,
    correct_answer: 'Hamlet',
    incorrect_answers: ['Romeo y Julieta', 'Macbeth', 'El Rey Lear'],
  },
  {
    id: 10,
    difficulty: 'Fácil',
    question:
      '¿Cuál es la etiqueta correcta para insertar una línea horizontal en HTML?',
    category: HTML,
    correct_answer: '<hr>',
    incorrect_answers: ['<line>', '<br>', '<horizontal>'],
  },
  {
    id: 11,
    difficulty: 'Fácil',
    question:
      '¿Qué propiedad CSS se utiliza para cambiar el color de fondo de un elemento?',
    category: CSS,
    correct_answer: 'background-color',
    incorrect_answers: ['color', 'font-color', 'bgcolor'],
  },
  {
    id: 12,
    difficulty: 'Fácil',
    question: '¿Cómo se define un enlace en HTML?',
    category: HTML,
    correct_answer: '<a href="url">Texto del enlace</a>',
    incorrect_answers: [
      '<link url="url">Texto del enlace</link>',
      '<href="url">Texto del enlace</href>',
      '<anchor url="url">Texto del enlace</anchor>',
    ],
  },
  {
    id: 13,
    difficulty: 'Fácil',
    question:
      '¿Cuál es la unidad de medida para el tamaño de fuente que se basa en el tamaño del texto del elemento padre?',
    category: CSS,
    correct_answer: 'em',
    incorrect_answers: ['px', 'rem', 'pt'],
  },
  {
    id: 14,
    difficulty: 'Fácil',
    question:
      '¿Qué atributo HTML se utiliza para definir el texto alternativo de una imagen?',
    category: HTML,
    correct_answer: 'alt',
    incorrect_answers: ['title', 'description', 'text'],
  },
  {
    id: 15,
    difficulty: 'Fácil',
    question: "¿Quién escribió la obra 'Don Quijote de la Mancha'?",
    category: literatura,
    correct_answer: 'Miguel de Cervantes',
    incorrect_answers: [
      'Federico García Lorca',
      'Gabriel García Márquez',
      'Pablo Neruda',
    ],
  },
  {
    id: 16,
    difficulty: 'Fácil',
    question: '¿Cómo se hace una lista no ordenada en HTML?',
    category: HTML,
    correct_answer: '<p>',
    incorrect_answers: ['<par>', '<para>', '<paragraph>'],
  },
  {
    id: 17,
    difficulty: 'Medio',
    question: '¿Cuál es el país más poblado del mundo?',
    category: geografia,
    correct_answer: 'China',
    incorrect_answers: ['India', 'Estados Unidos', 'Brasil'],
  },
  {
    id: 18,
    difficulty: 'Fácil',
    question:
      '¿Cuál de las siguientes es una forma correcta de declarar una variable en JavaScript?',
    category: JS,
    correct_answer: 'var',
    incorrect_answers: ['let', 'const', 'variable'],
  },
  {
    id: 19,
    difficulty: 'Fácil',
    question: '¿Qué etiqueta se utiliza para crear una tabla en HTML?',
    category: HTML,
    correct_answer: '<table>',
    incorrect_answers: ['<tab>', '<tbl>', '<grid>'],
  },
  {
    id: 20,
    difficulty: 'Fácil',
    question: '¿Quién es el autor de la novela "El viejo y el mar"?',
    category: literatura,
    correct_answer: 'Ernest Hemingway',
    incorrect_answers: [
      'William Shakespeare',
      'J.K. Rowling',
      'F. Scott Fitzgerald',
    ],
  },
  {
    id: 21,
    difficulty: 'Fácil',
    question:
      '¿Cuál es la etiqueta HTML correcta para agregar un encabezado de nivel 1?',
    category: HTML,
    correct_answer: '<h1>',
    incorrect_answers: ['<header1>', '<head1>', '<heading1>'],
  },
  {
    id: 22,
    difficulty: 'Medio',
    question: '¿Quién es el creador del sistema operativo Linux?',
    category: tecnologia,
    correct_answer: 'Linus Torvalds',
    incorrect_answers: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg'],
  },
  {
    id: 23,
    difficulty: 'Medio',
    question: '¿En qué año terminó la Segunda Guerra Mundial?',
    category: historia,
    correct_answer: '1945',
    incorrect_answers: ['1939', '1941', '1943'],
  },
  {
    id: 24,
    difficulty: 'Fácil',
    question: '¿Cómo se inserta una imagen en una página HTML?',
    category: HTML,
    correct_answer: '<img src="url_de_la_imagen" alt="texto alternativo">',
    incorrect_answers: [
      '<image src="url_de_la_imagen" alt="texto alternativo">',
      '<pic src="url_de_la_imagen" alt="texto alternativo">',
      '<src="url_de_la_imagen" alt="texto alternativo">',
    ],
  },
  {
    id: 25,
    difficulty: 'Medio',
    question:
      "¿Qué escritor es conocido por haber escrito 'Cien años de soledad'?",
    category: literatura,
    correct_answer: 'Gabriel García Márquez',
    incorrect_answers: ['Jorge Luis Borges', 'Pablo Neruda', 'Julio Cortázar'],
  },
  {
    id: 26,
    difficulty: 'Difícil',
    question: '¿Qué país es el más grande en términos de superficie terrestre?',
    category: geografia,
    correct_answer: 'Rusia',
    incorrect_answers: ['Estados Unidos', 'China', 'Australia'],
  },
  {
    id: 27,
    difficulty: 'Medio',
    question: '¿Cuál es la capital de Canadá?',
    category: geografia,
    correct_answer: 'Ottawa',
    incorrect_answers: ['Toronto', 'Montreal', 'Vancouver'],
  },
  {
    id: 28,
    difficulty: 'Fácil',
    question: '¿Cuál es la etiqueta HTML para agregar un formulario?',
    category: HTML,
    correct_answer: '<form>',
    incorrect_answers: ['<frm>', '<formulario>', '<formtag>'],
  },
  {
    id: 29,
    difficulty: 'Fácil',
    question:
      '¿Qué propiedad se usa para alinear texto en el centro de un elemento?',
    category: CSS,
    correct_answer: 'text-align',
    incorrect_answers: ['align-text', 'center', 'justify'],
  },
  {
    id: 30,
    difficulty: 'Fácil',
    question: '¿En qué año ocurrió la Revolución Francesa?',
    category: historia,
    correct_answer: '1789',
    incorrect_answers: ['1848', '1917', '1492'],
  },
  // -------------------
  {
    id: 31,
    difficulty: 'Fácil',
    category: tecnologia,
    question: '¿Qué significa la sigla HTML?',
    correct_answer: 'HyperText Markup Language',
    incorrect_answers: [
      'Hyperlinks and Text Markup Language',
      'Home Tool Markup Language',
      'Hyperlinking Text Markup Language',
    ],
  },
  {
    id: 32,
    difficulty: 'Fácil',
    category: tecnologia,
    question: '¿Cuál es el navegador web más utilizado en el mundo?',
    correct_answer: 'Google Chrome',
    incorrect_answers: ['Safari', 'Firefox', 'Internet Explorer'],
  },
  {
    id: 33,
    difficulty: 'Fácil',
    category: tecnologia,
    question:
      '¿Qué lenguaje de programación es más utilizado para el desarrollo web?',
    correct_answer: 'JavaScript',
    incorrect_answers: ['Python', 'Java', 'C++'],
  },
  {
    id: 34,
    difficulty: 'Medio',
    category: tecnologia,
    question: '¿Qué es un servidor web?',
    correct_answer: 'Un programa que recibe y procesa solicitudes HTTP',
    incorrect_answers: [
      'Un programa que envía correos electrónicos',
      'Un programa que protege la privacidad de los usuarios en línea',
      'Un programa que realiza operaciones matemáticas complejas',
    ],
  },
  {
    id: 35,
    difficulty: 'Medio',
    category: tecnologia,
    question: '¿Qué es un ataque de phishing?',
    correct_answer:
      'Un intento de obtener información confidencial a través de un correo electrónico falso',
    incorrect_answers: [
      'Un virus que daña los archivos del ordenador',
      'Un tipo de ataque DDoS',
      'Un intento de secuestrar el tráfico de internet',
    ],
  },
  {
    id: 36,
    difficulty: 'Medio',
    category: tecnologia,
    question: '¿Qué es un archivo CSV?',
    correct_answer: 'Un archivo de texto con valores separados por comas',
    incorrect_answers: [
      'Un archivo de audio comprimido',
      'Un archivo de imagen en formato vectorial',
      'Un archivo de vídeo de alta definición',
    ],
  },
  {
    id: 37,
    difficulty: 'Difícil',
    category: tecnologia,
    question: '¿Qué es un algoritmo de cifrado asimétrico?',
    correct_answer: 'Un método de cifrado que utiliza dos claves diferentes',
    incorrect_answers: [
      'Un método de cifrado que utiliza la misma clave para cifrar y descifrar',
      'Un método de cifrado que no utiliza claves',
      'Un método de cifrado que solo se utiliza en aplicaciones militares',
    ],
  },
  {
    id: 38,
    difficulty: 'Difícil',
    category: tecnologia,
    question: '¿Qué es una red privada virtual (VPN)?',
    correct_answer:
      'Una conexión segura a una red privada a través de internet',
    incorrect_answers: [
      'Una red de computadoras en una organización',
      'Una red de computadoras conectadas a internet',
      'Una red de computadoras que solo utiliza tecnología inalámbrica',
    ],
  },
  {
    id: 39,
    difficulty: 'Difícil',
    question: '¿En qué año se produjo la Guerra de los Cien Años?',
    category: historia,
    correct_answer: '1337',
    incorrect_answers: ['1066', '1415', '1642'],
  },
  {
    id: 40,
    difficulty: 'Fácil',
    question: '¿En qué año se produjo el ataque a Pearl Harbor?',
    category: historia,
    correct_answer: '1941',
    incorrect_answers: ['1939', '1942', '1945'],
  },
  {
    id: 41,
    difficulty: 'Medio',
    question: '¿Qué tratado dio fin a la Primera Guerra Mundial?',
    category: historia,
    correct_answer: 'Tratado de Versalles',
    incorrect_answers: [
      'Tratado de Tordesillas',
      'Tratado de Westfalia',
      'Tratado de Nankín',
    ],
  },
  {
    id: 42,
    difficulty: 'Difícil',
    question: '¿Quién fue el último emperador de la Dinastía Qing en China?',
    category: historia,
    correct_answer: 'Puyi',
    incorrect_answers: ['Hongwu', 'Wuzong', 'Kangxi'],
  },
  {
    id: 43,
    difficulty: 'Fácil',
    question:
      '¿Cuál fue el nombre de la primera expedición de Cristóbal Colón?',
    category: historia,
    correct_answer: 'La Santa María',
    incorrect_answers: ['La Pinta', 'La Niña', 'La Santísima Trinidad'],
  },
  {
    id: 44,
    difficulty: 'Medio',
    question:
      '¿Cuál fue el primer país en enviar un objeto hecho por el hombre a la luna?',
    category: historia,
    correct_answer: 'Estados Unidos',
    incorrect_answers: ['Unión Soviética', 'China', 'Japón'],
  },
  {
    id: 45,
    difficulty: 'Difícil',
    question:
      '¿Cuál fue la primera ciudad en el mundo en tener una población de más de un millón de habitantes?',
    category: historia,
    correct_answer: 'Roma',
    incorrect_answers: ['Atenas', 'Babilonia', 'Nínive'],
  },
  {
    id: 46,
    difficulty: 'Fácil',
    question: '¿Quién fue el primer presidente de los Estados Unidos?',
    category: historia,
    correct_answer: 'George Washington',
    incorrect_answers: [
      'Thomas Jefferson',
      'Abraham Lincoln',
      'Franklin D. Roosevelt',
    ],
  },
  {
    id: 47,
    difficulty: 'Medio',
    question: '¿Cuál fue la primera dinastía en gobernar en China?',
    category: historia,
    correct_answer: 'Xia',
    incorrect_answers: ['Han', 'Tang', 'Song'],
  },
  {
    id: 48,
    difficulty: 'Fácil',
    question: '¿Quién escribió la obra "Don Quijote de la Mancha"?',
    category: literatura,
    correct_answer: 'Miguel de Cervantes',
    incorrect_answers: [
      'Gabriel García Márquez',
      'Jorge Luis Borges',
      'Pablo Neruda',
    ],
  },
  {
    id: 49,
    difficulty: 'Medio',
    question:
      '¿Cuál de las siguientes novelas es escrita por Gabriel García Márquez?',
    category: literatura,
    correct_answer: 'Cien años de soledad',
    incorrect_answers: [
      'Rayuela',
      'La ciudad y los perros',
      'La casa de los espíritus',
    ],
  },
  {
    id: 50,
    difficulty: 'Difícil',
    question: '¿Quién escribió "La metamorfosis"?',
    category: literatura,
    correct_answer: 'Franz Kafka',
    incorrect_answers: ['Virginia Woolf', 'James Joyce', 'F. Scott Fitzgerald'],
  },
  {
    id: 51,
    difficulty: 'Fácil',
    question: '¿Quién escribió "El retrato de Dorian Gray"?',
    category: literatura,
    correct_answer: 'Oscar Wilde',
    incorrect_answers: ['Edgar Allan Poe', 'Emily Bronte', 'Charles Dickens'],
  },
  {
    id: 52,
    difficulty: 'Medio',
    question:
      '¿Cuál de las siguientes obras no fue escrita por William Shakespeare?',
    category: literatura,
    correct_answer: 'Moby Dick',
    incorrect_answers: ['Hamlet', 'Macbeth', 'Otelo'],
  },
  {
    id: 53,
    difficulty: 'Difícil',
    question:
      '¿Cuál de las siguientes obras de José Saramago recibió el Premio Nobel de Literatura?',
    category: literatura,
    correct_answer: 'Ensayo sobre la ceguera',
    incorrect_answers: [
      'La caverna',
      'El evangelio según Jesucristo',
      'Las intermitencias de la muerte',
    ],
  },
  {
    id: 54,
    difficulty: 'Fácil',
    question: '¿Quién escribió la novela "El guardián entre el centeno"?',
    category: literatura,
    correct_answer: 'J.D. Salinger',
    incorrect_answers: [
      'F. Scott Fitzgerald',
      'Ernest Hemingway',
      'Tennessee Williams',
    ],
  },
  {
    id: 55,
    difficulty: 'Difícil',
    question: '¿Cuál es el país más grande de África?',
    category: geografia,
    correct_answer: 'Argelia',
    incorrect_answers: ['Sudán', 'Libia', 'República Democrática del Congo'],
  },
  {
    id: 56,
    difficulty: 'Fácil',
    question: '¿Cuál es el país más grande del mundo?',
    category: geografia,
    correct_answer: 'Rusia',
    incorrect_answers: ['China', 'Estados Unidos', 'Canadá'],
  },
  {
    id: 57,
    difficulty: 'Medio',
    question: '¿En qué continente se encuentra el lago Baikal?',
    category: geografia,
    correct_answer: 'Asia',
    incorrect_answers: ['Europa', 'África', 'América del Sur'],
  },
  {
    id: 58,
    difficulty: 'Medio',
    question: '¿Cuál es el país más poblado del mundo?',
    category: geografia,
    correct_answer: 'China',
    incorrect_answers: ['India', 'Estados Unidos', 'Indonesia'],
  },
  {
    id: 59,
    difficulty: 'Difícil',
    question: '¿Cuál es la montaña más alta del mundo?',
    category: geografia,
    correct_answer: 'El Monte Everest',
    incorrect_answers: ['El K2', 'El Mont Blanc', 'El Aconcagua'],
  },
  {
    id: 60,
    difficulty: 'Difícil',
    question: '¿Cuál es el país más pequeño del mundo?',
    category: geografia,
    correct_answer: 'El Vaticano',
    incorrect_answers: ['Mónaco', 'Nauru', 'Tuvalu'],
  },
  {
    id: 61,
    difficulty: 'Medio',
    question: '¿Cuál es el país más extenso de África?',
    category: geografia,
    correct_answer: 'Argelia',
    incorrect_answers: ['Nigeria', 'Egipto', 'Sudáfrica'],
  },
  {
    id: 62,
    difficulty: 'Fácil',
    question:
      '¿Qué valor de la propiedad "display" se utiliza para hacer que un elemento no se muestre?',
    category: CSS,
    correct_answer: 'none',
    incorrect_answers: ['block', 'inline', 'hidden'],
  },
  {
    id: 63,
    difficulty: 'Fácil',
    question:
      '¿Qué propiedad se utiliza para establecer el margen externo de un elemento?',
    category: CSS,
    correct_answer: 'margin',
    incorrect_answers: ['padding', 'border', 'spacing'],
  },
  {
    id: 64,
    difficulty: 'Fácil',
    question: '¿Qué propiedad CSS se utiliza para agregar sombra a un texto?',
    category: CSS,
    correct_answer: 'text-shadow',
    incorrect_answers: ['box-shadow', 'shadow', 'font-shadow'],
  },
  {
    id: 65,
    difficulty: 'Fácil',
    question:
      '¿Cuál es la propiedad utilizada para cambiar la imagen de fondo de un elemento?',
    category: CSS,
    correct_answer: 'background-image',
    incorrect_answers: ['image', 'background', 'bg-image'],
  },
  {
    id: 66,
    difficulty: 'Fácil',
    question: '¿Qué propiedad se utiliza para cambiar el estilo de una fuente?',
    category: CSS,
    correct_answer: 'font-family',
    incorrect_answers: ['font-style', 'text-font', 'font'],
  },
  {
    id: 67,
    difficulty: 'Fácil',
    question:
      '¿Qué propiedad CSS se utiliza para redondear las esquinas de un elemento?',
    category: CSS,
    correct_answer: 'border-radius',
    incorrect_answers: ['border-round', 'corner-radius', 'radius'],
  },
  {
    id: 68,
    difficulty: 'Fácil',
    question:
      '¿Qué propiedad se usa para controlar la opacidad de un elemento?',
    category: CSS,
    correct_answer: 'opacity',
    incorrect_answers: ['transparency', 'visibility', 'filter'],
  },
  {
    id: 69,
    difficulty: 'Media',
    question:
      '¿Cuál es la propiedad CSS que se utiliza para cambiar el tamaño del texto?',
    category: CSS,
    correct_answer: 'font-size',
    incorrect_answers: ['text-size', 'font-weight', 'text-style'],
  },
  {
    id: 70,
    difficulty: 'Fácil',
    question:
      '¿Qué método se utiliza para convertir una cadena a un número en JavaScript?',
    category: JS,
    correct_answer: 'parseInt',
    incorrect_answers: ['Number', 'convertToInt', 'toInteger'],
  },
  {
    id: 71,
    difficulty: 'Fácil',
    question: '¿Cuál de los siguientes es un tipo de dato en JavaScript?',
    category: JS,
    correct_answer: 'boolean',
    incorrect_answers: ['character', 'float', 'stringify'],
  },
  {
    id: 72,
    difficulty: 'Fácil',
    question:
      '¿Qué símbolo se utiliza para hacer comentarios de una sola línea en JavaScript?',
    category: JS,
    correct_answer: '//',
    incorrect_answers: ['#', '/*', '<!--'],
  },
  {
    id: 73,
    difficulty: 'Fácil',
    question: '¿Cómo se define una función en JavaScript?',
    category: JS,
    correct_answer: 'function myFunction() {}',
    incorrect_answers: [
      'function: myFunction() {}',
      'def myFunction() {}',
      'myFunction() => {}',
    ],
  },
  {
    id: 74,
    difficulty: 'Fácil',
    question: '¿Cuál es el resultado de 2 + "2" en JavaScript?',
    category: JS,
    correct_answer: '22',
    incorrect_answers: ['4', 'Error', '22 como número'],
  },
  {
    id: 75,
    difficulty: 'Fácil',
    question:
      '¿Qué función se usa para mostrar un mensaje en un cuadro de alerta?',
    category: JS,
    correct_answer: 'alert()',
    incorrect_answers: ['msg()', 'popup()', 'message()'],
  },
  {
    id: 76,
    difficulty: 'Fácil',
    question:
      '¿Cuál es el operador utilizado para comparar valores y tipos en JavaScript?',
    category: JS,
    correct_answer: '===',
    incorrect_answers: ['==', '!==', '=>'],
  },
  {
    id: 77,
    difficulty: 'Fácil',
    question:
      '¿Qué método se usa para agregar un elemento al final de un array?',
    category: JS,
    correct_answer: 'push()',
    incorrect_answers: ['add()', 'append()', 'insert()'],
  },
  {
    id: 78,
    difficulty: 'Fácil',
    question: '¿Qué objeto se utiliza para trabajar con fechas en JavaScript?',
    category: JS,
    correct_answer: 'Date',
    incorrect_answers: ['Time', 'Calendar', 'Moment'],
  },
  {
    id: 79,
    difficulty: 'Media',
    question: '¿Cuál es el resultado de typeof NaN en JavaScript?',
    category: JS,
    correct_answer: 'number',
    incorrect_answers: ['undefined', 'NaN', 'string'],
  },
  {
    id: 80,
    difficulty: 'Media',
    question:
      '¿Cuál es el atributo correcto para abrir un enlace en una nueva pestaña o ventana?',
    category: HTML,
    correct_answer: 'target="_blank"',
    incorrect_answers: ['new="_tab"', 'open="new"', 'window="new"'],
  },
  {
    id: 81,
    category: HTML,
    difficulty: 'Medio',
    question: '¿Cómo se especifica un fondo de color para una página HTML?',
    correct_answer: '<body style="background-color:lightblue;">',
    incorrect_answers: [
      '<background color="lightblue">',
      '<body bgcolor="lightblue">',
      '<body color="lightblue">',
    ],
  },
  {
    id: 82,
    category: HTML,
    difficulty: 'Media',
    question:
      '¿Qué etiqueta se usa para crear una celda de encabezado en una tabla HTML?',
    correct_answer: '<th>',
    incorrect_answers: ['<thead>', '<header>', '<trh>'],
  },
  {
    id: 83,
    difficulty: 'Fácil',
    question: '¿Qué es el acrónimo "CPU" en inglés?',
    category: tecnologia,
    correct_answer: 'Central Processing Unit',
    incorrect_answers: [
      'Computer Personal Unit',
      'Central Personal Unit',
      'Computer Processing Unit',
    ],
  },
  {
    id: 84,
    difficulty: 'Medio',
    question:
      '¿Cuál es el nombre de la primera computadora electrónica digital?',
    category: tecnologia,
    correct_answer: 'ENIAC',
    incorrect_answers: ['UNIVAC', 'COLOSSUS', 'EDSAC'],
  },
  {
    id: 85,
    category: HTML,
    difficulty: 'Media',
    question: '¿Cómo se especifica una lista ordenada en HTML?',
    correct_answer: '<ol><li>Elemento 1</li><li>Elemento 2</li></ol>',
    incorrect_answers: [
      '<ul><li>Elemento 1</li><li>Elemento 2</li></ul>',
      '<ordered><li>Elemento 1</li><li>Elemento 2</li></ordered>',
      '<list><li>Elemento 1</li><li>Elemento 2</li></list>',
    ],
  },
  {
    id: 86,
    category: HTML,
    difficulty: 'Media',
    question:
      '¿Qué etiqueta HTML se utiliza para definir una sección independiente de contenido en un documento HTML?',
    correct_answer: '<section>',
    incorrect_answers: ['<div>', '<article>', '<header>'],
  },
  {
    id: 87,
    category: HTML,
    difficulty: 'Media',
    question: '¿Cuál es la forma correcta de crear un comentario en HTML?',
    correct_answer: '<!-- Este es un comentario -->',
    incorrect_answers: [
      '/* Este es un comentario */',
      '// Este es un comentario',
      '<-- Este es un comentario -->',
    ],
  },
  {
    id: 88,
    category: HTML,
    difficulty: 'Media',
    question: '¿Cómo se define una celda en una tabla HTML?',
    correct_answer: '<td>',
    incorrect_answers: ['<tr>', '<cell>', '<tabledata>'],
  },
  {
    id: 89,
    category: HTML,
    difficulty: 'Media',
    question:
      '¿Qué atributo HTML se usa para combinar celdas horizontalmente en una tabla?',
    correct_answer: 'colspan',
    incorrect_answers: ['rowspan', 'merge', 'span'],
  },
  {
    id: 90,
    category: HTML,
    difficulty: 'Media',
    question: '¿Cuál es la etiqueta HTML correcta para reproducir un video?',
    correct_answer: '<video>',
    incorrect_answers: ['<vid>', '<media>', '<movie>'],
  },
  {
    id: 91,
    category: HTML,
    difficulty: 'Media',
    question: '¿Cómo se define un área de texto en un formulario HTML?',
    correct_answer: '<textarea>',
    incorrect_answers: [
      '<input type="textarea">',
      '<textbox>',
      '<input type="text">',
    ],
  },
  {
    id: 92,
    category: HTML,
    difficulty: 'Media',
    question:
      '¿Qué atributo se utiliza para establecer un enlace anclado (bookmark) dentro de una página HTML?',
    correct_answer: 'id',
    incorrect_answers: ['name', 'href', 'link'],
  },
  {
    id: 93,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Cuál es la propiedad CSS que se utiliza para cambiar el tamaño del texto?',
    correct_answer: 'font-size',
    incorrect_answers: ['text-size', 'font-weight', 'text-style'],
  },
  {
    id: 94,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Qué valor de la propiedad "display" se utiliza para crear un contenedor flexible?',
    correct_answer: 'flex',
    incorrect_answers: ['grid', 'block', 'inline'],
  },
  {
    id: 95,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Qué propiedad se usa para controlar el espaciado interno de un elemento?',
    correct_answer: 'padding',
    incorrect_answers: ['margin', 'border', 'spacing'],
  },
  {
    id: 96,
    category: CSS,
    difficulty: 'Media',
    question: '¿Cómo se puede aplicar un efecto de transición en CSS?',
    correct_answer: 'transition',
    incorrect_answers: ['animation', 'transform', 'hover'],
  },
  {
    id: 97,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Qué propiedad se utiliza para aplicar un efecto de desenfoque a un elemento?',
    correct_answer: 'filter',
    incorrect_answers: ['blur', 'opacity', 'shadow'],
  },
  {
    id: 98,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Cuál es la propiedad para establecer la posición de un elemento en CSS?',
    correct_answer: 'position',
    incorrect_answers: ['align', 'layout', 'float'],
  },
  {
    id: 99,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Qué propiedad se utiliza para definir un borde alrededor de un elemento?',
    correct_answer: 'border',
    incorrect_answers: ['outline', 'margin', 'padding'],
  },
  {
    id: 100,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Cómo se define un estilo para un elemento al pasar el ratón sobre él?',
    correct_answer: 'pseudo-clase :hover',
    incorrect_answers: ['pseudo-element :focus', 'media query', 'keyframes'],
  },
  {
    id: 101,
    category: CSS,
    difficulty: 'Media',
    question:
      '¿Qué propiedad se utiliza para establecer la dirección del texto?',
    correct_answer: 'direction',
    incorrect_answers: ['text-align', 'text-direction', 'flow'],
  },
  {
    id: 102,
    category: CSS,
    difficulty: 'Media',
    question: '¿Cuál es la forma correcta de aplicar un color RGBA en CSS?',
    correct_answer: 'rgba(255, 0, 0, 0.5)',
    incorrect_answers: [
      'rgb(255, 0, 0, 0.5)',
      'rgba(255, 0, 0)',
      'rgba(255, 0, 0, 50)',
    ],
  },
  {
    id: 103,
    category: JS,
    difficulty: 'Media',
    question:
      '¿Qué método se utiliza para convertir un objeto JSON en una cadena en JavaScript?',
    correct_answer: 'JSON.stringify()',
    incorrect_answers: ['JSON.parse()', 'Object.toString()', 'Stringify()'],
  },
  {
    id: 104,
    category: JS,
    difficulty: 'Media',
    question:
      '¿Qué palabra clave se usa para declarar una variable que no puede ser reasignada?',
    correct_answer: 'const',
    incorrect_answers: ['let', 'var', 'immutable'],
  },
  {
    id: 105,
    category: JS,
    difficulty: 'Media',
    question: '¿Cuál es la forma correcta de crear un objeto en JavaScript?',
    correct_answer: 'let obj = {};',
    incorrect_answers: [
      'let obj = [];',
      'let obj = ();',
      'let obj = new Object();',
    ],
  },
  {
    id: 106,
    category: JS,
    difficulty: 'Media',
    question:
      '¿Qué método se usa para eliminar el último elemento de un array?',
    correct_answer: 'pop()',
    incorrect_answers: ['shift()', 'remove()', 'slice()'],
  },
  {
    id: 107,
    category: JS,
    difficulty: 'Media',
    question: '¿Cuál es el resultado de `0 == "0"` en JavaScript?',
    correct_answer: 'true',
    incorrect_answers: ['false', 'undefined', 'NaN'],
  },
  {
    id: 108,
    category: JS,
    difficulty: 'Media',
    question:
      '¿Qué evento se usa para detectar cuando un usuario envía un formulario?',
    correct_answer: 'submit',
    incorrect_answers: ['click', 'change', 'focus'],
  },
  {
    id: 109,
    category: JS,
    difficulty: 'Media',
    question: '¿Qué método se utiliza para recorrer cada elemento de un array?',
    correct_answer: 'forEach()',
    incorrect_answers: ['map()', 'filter()', 'each()'],
  },
  {
    id: 110,
    category: JS,
    difficulty: 'Media',
    question: '¿Cuál es el alcance de una variable declarada con `let`?',
    correct_answer: 'bloque',
    incorrect_answers: ['global', 'función', 'módulo'],
  },
  {
    id: 111,
    category: JS,
    difficulty: 'Media',
    question:
      '¿Qué estructura se utiliza para manejar excepciones en JavaScript?',
    correct_answer: 'try...catch',
    incorrect_answers: ['if...else', 'switch', 'throw'],
  },
];
